//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by a Div CS Mapper Generator.
//    Runtime Version: 1.0.0
//    See: https://divengine.org
//
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Custom Mapper: EmployeeMapper

using Divengine.CSMapperGenerator.Example.Model;

namespace Divengine.CSMapperGenerator.Example.Mappers
{
    public class EmployeeMapper
    {
        public static Address Clone(Address fromEntity)
        {
            if (fromEntity == null)
            {
                return null;
            }

            Address toEntity = new Address();
            toEntity.Street = fromEntity.Street;
            toEntity.City = fromEntity.City;
            toEntity.State = fromEntity.State;
            toEntity.ZipCode = fromEntity.ZipCode;
            return toEntity;
        }

        public static EmployeeDto Clone(EmployeeDto fromEntity)
        {
            if (fromEntity == null)
            {
                return null;
            }

            EmployeeDto toEntity = new EmployeeDto();
            toEntity.Id = fromEntity.Id;
            toEntity.FullName = fromEntity.FullName;
            toEntity.Department = fromEntity.Department;
            toEntity.Age = fromEntity.Age;
            toEntity.Address = fromEntity.Address;
            return toEntity;
        }

        public static Employee Clone(Employee fromEntity)
        {
            if (fromEntity == null)
            {
                return null;
            }

            Employee toEntity = new Employee();
            toEntity.Id = fromEntity.Id;
            toEntity.FirstName = fromEntity.FirstName;
            toEntity.LastName = fromEntity.LastName;
            toEntity.DateOfBirth = fromEntity.DateOfBirth;
            toEntity.Department = fromEntity.Department;
            toEntity.Address = fromEntity.Address;
            return toEntity;
        }

        public static EmployeeDto Map(Employee fromEntity)
        {
            if (fromEntity == null)
            {
                return null;
            }

            EmployeeDto toEntity = new EmployeeDto();
            toEntity.Id = fromEntity.Id;
            toEntity.Department = fromEntity.Department;
            toEntity.Address = fromEntity.Address;
            return toEntity;
        }

        public static Employee Map(EmployeeDto fromEntity)
        {
            if (fromEntity == null)
            {
                return null;
            }

            Employee toEntity = new Employee();
            toEntity.Id = fromEntity.Id;
            toEntity.Department = fromEntity.Department;
            toEntity.Address = fromEntity.Address;
            return toEntity;
        }
    }
}